entrypoint: bundle exec rackup --port $PORT
env: flex
# runtime: ruby27
runtime: ruby

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.50
  min_instances: 1
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50


beta_settings:
  cloud_sql_instances: unify-309723:us-west2:unify-sql

env_variables:
  SECRET_KEY_BASE: 0e127016dff33c942b52096d5dd185124b5f2c8205aa13feea18ff36851b626d9db331f0b0cac4b007d8497c7a484028f2a00aac6ba76f39dbd4355336c5f36f